name: DateTime-Functions
version: 0.01
abstract: Procedural interface to DateTime functions
author: Autrijus Tang (autrijus@autrijus.org)
license: unknown
distribution_type: module
requires:
  DateTime: 0
no_index:
  directory:
    - inc
private:
  directory:
    - inc
generated_by: Module::Install version 0.27
